name: cicd
on:
  push:
    paths:
      - /**
      - .github/workflows/ci-cd.yml
jobs:
  - name: Deploy to Cloud Run
    id: deploy
    uses: google-github-actions/deploy-cloudrun@main
    with:
      service: ebiz-shop
      image: europe-central2-docker.pkg.dev/steel-beanbag-294917/ebiznes/ebiz-shop
      credentials: ${{ secrets.GCP_SA_KEY }}